db = db.getSiblingDB('technology-radar');

db.technologies.deleteMany({});

db.technologies.insertMany([
  {
    name: 'React',
    category: 'Languages & Frameworks',
    ring: 'Adopt',
    description: 'A JavaScript library for building user interfaces',
    reason: 'Widely adopted, great ecosystem, strong community support',
    createdAt: new Date('2024-01-15'),
    changedAt: new Date('2024-01-15'),
    isPublished: true,
  },
  {
    name: 'Angular',
    category: 'Languages & Frameworks',
    ring: 'Adopt',
    description: 'Platform for building web applications',
    reason: 'Enterprise-ready, comprehensive framework with built-in features',
    createdAt: new Date('2024-01-20'),
    changedAt: new Date('2024-01-20'),
    isPublished: true,
  },
  {
    name: 'Docker',
    category: 'Tools',
    ring: 'Adopt',
    description:
      'Platform for developing, shipping, and running applications in containers',
    reason: 'Industry standard for containerization, simplifies deployment',
    createdAt: new Date('2024-02-01'),
    changedAt: new Date('2024-02-01'),
    isPublished: true,
  },
  {
    name: 'Deno',
    category: 'Platforms',
    ring: 'Trial',
    description: 'A modern runtime for JavaScript and TypeScript',
    reason: 'Interesting alternative to Node.js, still evaluating maturity',
    createdAt: new Date('2024-02-10'),
    changedAt: new Date('2024-02-10'),
    isPublished: true,
  },
  {
    name: 'GraphQL',
    category: 'Techniques',
    ring: 'Assess',
    description: 'Query language for APIs',
    reason: 'Exploring for future API development, needs more evaluation',
    createdAt: new Date('2024-02-15'),
    changedAt: new Date('2024-02-15'),
    isPublished: false,
  },
  {
    name: 'WebAssembly',
    category: 'Techniques',
    ring: 'Assess',
    description: 'Binary instruction format for stack-based virtual machine',
    reason: 'Monitoring for performance-critical applications',
    createdAt: new Date('2024-02-20'),
    changedAt: new Date('2024-02-20'),
    isPublished: true,
  },
  {
    name: 'jQuery',
    category: 'Languages & Frameworks',
    ring: 'Hold',
    description: 'Fast, small JavaScript library',
    reason:
      'Legacy framework, moving away from it in favor of modern alternatives',
    createdAt: new Date('2024-01-10'),
    changedAt: new Date('2024-01-10'),
    isPublished: true,
  },
  {
    name: 'Kubernetes',
    category: 'Platforms',
    ring: 'Trial',
    description: 'Container orchestration platform',
    reason: 'Testing for microservices deployment scenarios',
    createdAt: new Date('2024-02-25'),
    changedAt: new Date('2024-02-25'),
    isPublished: true,
  },
  {
    name: 'Java',
    category: 'Languages & Frameworks',
    ring: 'Adopt',
    description: 'Object Oriented, Multi Platform Language',
    reason: 'Well supported, industry standard, large ecosystem',
    createdAt: new Date('2024-02-28'),
    isPublished: true,
    __v: 0,
  },
  {
    name: 'Kotlin',
    category: 'Languages & Frameworks',
    ring: 'Trial',
    description: 'modern, statically typed, runs on JVM',
    reason:
      'Interoperability with Java, more fun to write than java, widely used in android development',
    isPublished: true,
    createdAt: new Date('2024-02-08'),
    __v: 0,
  },
  {
    name: 'Code Review',
    category: 'Techniques',
    ring: 'Adopt',
    description:
      'Code written by one developer gets looked at and reviewed by another',
    reason: 'Improves code quality overall and catches errors early',
    createdAt: new Date('2024-02-09'),
    isPublished: true,
    __v: 0,
  },
  {
    name: 'Arc42 Documentation',
    category: 'Techniques',
    ring: 'Hold',
    description: 'Template to create technical documentation',
    reason:
      'Ensures all important aspects are documented, Uniform contents over all products.',
    createdAt: new Date('2024-02-10'),
    isPublished: true,
    __v: 0,
  },
  {
    name: 'Pre-commit hooks',
    category: 'Techniques',
    ring: 'Trial',
    description: 'Git hook code validation',
    reason: 'Helps prevent commits of bad quality',
    createdAt: new Date('2024-02-11'),
    isPublished: true,
    __v: 0,
  },
  {
    name: 'Jira',
    category: 'Platforms',
    ring: 'Trial',
    description: 'Issue tracker for Scrum or Kanban',
    reason: 'Industry standard',
    createdAt: new Date('2024-02-12'),
    isPublished: true,
    __v: 0,
  },
  {
    name: 'Rust',
    category: 'Languages & Frameworks',
    ring: 'Assess',
    description: 'Open Source Multiparadigm System language.',
    reason: 'Type and memory safety, ideal for concurrency',
    createdAt: new Date('2024-02-13'),
    isPublished: false,
    __v: 0,
  },
  {
    name: 'Github',
    category: 'Platforms',
    ring: 'Assess',
    description: 'Cloud based hosting for software development using git.',
    reason: 'Allows us to store, share and work at code in collaboration',
    createdAt: new Date('2024-02-14'),
    isPublished: false,
    __v: 0,
  },
  {
    name: 'Scrum',
    category: 'Tools',
    ring: 'Adopt',
    description: 'Agile Framework for software development.',
    reason:
      'With our ever changing requirements, it makes sense to use an agile approach.',
    createdAt: new Date('2024-02-15'),
    isPublished: true,
    __v: 0,
  },
]);

print(
  'Database initialized with ' +
    db.technologies.countDocuments() +
    ' technologies',
);
